jobs:
  test-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Test'
          command: npx jest --coverage --ci
      - run:
          name: 'Lint'
          command: yarn lint

orbs:
  node: circleci/node@4.0.1

version: 2.1

workflows:
  test-lint:
    jobs:
      - test-lint
